server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: cryptoscore-backend
  
  datasource:
    url: jdbc:h2:mem:cryptoscore
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

jwt:
  secret: Y3J5cHRvc2NvcmUtc2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tMjAyNA==
  expiration: 86400000 # 24 hours

logging:
  level:
    com.cryptoscore: DEBUG
    org.springframework.security: DEBUG